apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-pvc
spec:
  storageClassName: ""
  volumeName: todo-app-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
